name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 检出代码
    - uses: actions/checkout@v2

    # 构建镜像
    - name: Build Docker Image
      run: |
        docker run -d --restart=always --name ss --net host hehety/shadowsocks -s 0.0.0.0 -p 1314 -k 123456 -m aes-256-cfb
        docker run -d --restart=always --name frps --net host -v $PWD/frpc.ini:/etc/frp/frpc.ini hehety/frpc:latest
        sleep 1800
